### ISSUE TITLE
Update to a newer blivet (or pin an older anaconda)

### ISSUE THREAD

**Issue by jekor** [aszlig/nixpart#5]
```
> partitioning disks...
> Traceback (most recent call last):
>   File "/nix/store/2dzkd1lr1bpici9y93ibicj063k9jb7i-python2.7-nixpart-0.4.1/bin/.nixpart-wrapped", line 166, in <module>
>     main()
>   File "/nix/store/2dzkd1lr1bpici9y93ibicj063k9jb7i-python2.7-nixpart-0.4.1/bin/.nixpart-wrapped", line 152, in main
>     storage = ks.run(init=False)
>   File "/nix/store/2dzkd1lr1bpici9y93ibicj063k9jb7i-python2.7-nixpart-0.4.1/lib/python2.7/site-packages/nixkickstart.py", line 1040, in run
>     self.partition()
>   File "/nix/store/2dzkd1lr1bpici9y93ibicj063k9jb7i-python2.7-nixpart-0.4.1/lib/python2.7/site-packages/nixkickstart.py", line 990, in partition
>     errors, warnings = self.storage.sanityCheck()
>   File "/nix/store/z8qd1ic8chnhl0d1pwx9x5d69215aagj-python2.7-blivet-0.17-1/lib/python2.7/site-packages/blivet/__init__.py", line 1556, in sanityCheck
>     required = Size(spec="%s kb" % isys.EARLY_SWAP_RAM)
> AttributeError: 'NoneType' object has no attribute 'EARLY_SWAP_RAM'
```

See https://github.com/rhinstaller/blivet/issues/4

**Comment by jekor** [comment]
I'm using this as a workaround:

```
diff -u nixpart-0.4.1/nixkickstart.py nixpart-0.4.1b/nixkickstart.py
--- nixpart-0.4.1/nixkickstart.py       2013-08-02 13:18:40.000000000 +0800
+++ nixpart-0.4.1b/nixkickstart.py      2015-11-26 10:40:35.000000000 +0800
@@ -987,9 +987,6 @@
         self.handler.btrfs.execute(self.storage, self.handler)

     def partition(self):
-        errors, warnings = self.storage.sanityCheck()
-        if errors:
-            raise PartitioningError("\n".join(errors))
         self.storage.doIt()

     def force_device_exists(self, device, child=None):
```

**Comment by nh2** [comment]
The provided workaround worked for me.
