### ISSUE TITLE
deploy to hetzner fails with `invalid device specification`

### ISSUE THREAD

**Issue by manveru** [aszlig/nixpart#7]
```
deployer@deploy:~/slipstream$ nixops deploy -d production
tokyo> creating an exclusive robot admin account for ‘tokyo’... done. 
tokyo> installing machine...
tokyo> rebooting machine ‘tokyo’ (x.x.x.x) into rescue system
tokyo> sending hard reset to robot... done.
tokyo> waiting for rescue system...[down].......................................................................................................[up]
tokyo> building Nix bootstrap installer... done. (/nix/store/6c47hh0f40yf40hln4sla314ihbd0xjn-hetzner-nixops-installer/bin/hetzner-bootstrap)
tokyo> creating nixbld group in rescue system... done.
tokyo> checking if tmpfs in rescue system is large enough... yes: 32078 MB
tokyo> copying bootstrap files to rescue system... done.
tokyo> partitioning disks... 
tokyo> Traceback (most recent call last):
tokyo>   File "/nix/store/bdbybjhccgdp2rqwsbs83ildilss7drm-python2.7-nixpart-0.4.1/bin/.nixpart-wrapped", line 166, in <module>
tokyo>     main()
tokyo>   File "/nix/store/bdbybjhccgdp2rqwsbs83ildilss7drm-python2.7-nixpart-0.4.1/bin/.nixpart-wrapped", line 152, in main
tokyo>     storage = ks.run(init=False)
tokyo>   File "/nix/store/bdbybjhccgdp2rqwsbs83ildilss7drm-python2.7-nixpart-0.4.1/lib/python2.7/site-packages/nixkickstart.py", line 1040, in run
tokyo>     self.partition()
tokyo>   File "/nix/store/bdbybjhccgdp2rqwsbs83ildilss7drm-python2.7-nixpart-0.4.1/lib/python2.7/site-packages/nixkickstart.py", line 993, in partition
tokyo>     self.storage.doIt()
tokyo>   File "/nix/store/cfb9msg4r518ihgxiyg8h2f7d9k7mwfv-python2.7-blivet-0.17-1/lib/python2.7/site-packages/blivet/__init__.py", line 310, in doIt
tokyo>     self.devicetree.processActions()
tokyo>   File "/nix/store/cfb9msg4r518ihgxiyg8h2f7d9k7mwfv-python2.7-blivet-0.17-1/lib/python2.7/site-packages/blivet/devicetree.py", line 237, in processActions
tokyo>     action.execute()
tokyo>   File "/nix/store/cfb9msg4r518ihgxiyg8h2f7d9k7mwfv-python2.7-blivet-0.17-1/lib/python2.7/site-packages/blivet/deviceaction.py", line 471, in execute
tokyo>     options=self.device.formatArgs)
tokyo>   File "/nix/store/cfb9msg4r518ihgxiyg8h2f7d9k7mwfv-python2.7-blivet-0.17-1/lib/python2.7/site-packages/blivet/formats/__init__.py", line 311, in create
tokyo>     raise FormatCreateError("invalid device specification", self.device)
tokyo> blivet.errors.FormatCreateError: ('invalid device specification', u'/dev/sdb2')
error: command ‘['ssh', '-oControlPath=/tmp/nixops-ssh-tmpwYD0U2/master-socket', '-p', '22', '-o', 'LogLevel=quiet', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'GlobalKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-p', '22', '-o', 'LogLevel=quiet', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'GlobalKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-x', 'root@x.x.x.x', '--', 'export LANG= LC_ALL= LC_TIME=; nixpart -p -']’ failed on machine ‘tokyo’ (exit code 1)
```

I tried two configurations:

    clearpart --all --initlabel --drives=sda,sdb

    part swap1 --recommended --label=swap1 --fstype=swap --ondisk=sda
    part swap2 --recommended --label=swap2 --fstype=swap --ondisk=sdb

    part raid.1 --grow --ondisk=sda
    part raid.2 --grow --ondisk=sdb

    raid / --level=1 --device=md0 --fstype=ext4 \
           --label=root raid.1 raid.2

and

    clearpart --all --initlabel --drives=sda,sdb

    part swap1 --recommended --label=swap1 --fstype=swap --ondisk=sda
    part swap2 --recommended --label=swap2 --fstype=swap --ondisk=sdb

    part btrfs.1 --grow --ondisk=sda
    part btrfs.2 --grow --ondisk=sdb

    btrfs / --data=1 --metadata=1 --label=root btrfs.1 btrfs.2

The harddisks are two "ATA Crucial_CT500MX2 (scsi)" with 500GB each. Installing another Linux distro like Ubuntu seems to work fine.

Any ideas how this could be fixed?

**Comment by domenkozar** [comment]
Possibly relevant: https://github.com/bcl/blivet/commit/88ed6c11db4debd750283040a68cb4c27bd5c8e4
